DROP TABLE IF EXISTS contacts;
CREATE TABLE contacts(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(30) ,
	phone VARCHAR(20) ,
	is_synced INTEGER CHECK(is_synced IN (0,1)) NOT NULL DEFAULT 0
);